add new entries and translations
FabulousCupcake/umamusume-db-translate pull request #64
Opened 2021-06-10 03:55 UTC by stardustichi

2021-06-10 07:28 UTC, robflop requested changes

2021-06-10 07:28 UTC, robflop commented on src/data/skill-desc.csv
> +"レース終盤のコーナーで先頭にいると\nこれ幸いと加速力を上げる","<size=22>On last corner, gain acceleration when leading in front</size>"
"Leading in front" sounds a bit unclear imo (how far "front"? and such). 先頭 means the vanguard, in this case the very front (1st position). I'd incorporate that.

2021-06-10 07:28 UTC, robflop commented on src/data/skill-desc.csv
> +"レース終盤のコーナーで先頭にいると\n加速力をわずかに上げる","<size=22>On last corner, slightly gain acceleration when leading in front</size>"
Same as the previous comment about 先頭

2021-06-10 07:28 UTC, robflop commented on src/data/trainer-title-requirements.csv
> +"タウラス杯で伝説的な成績を残そう","Leave a legendary achievement in the Taurus Hai"
残す is better translated as "achieve" here imo, as that sounds much more idiomatic and does not lose meaning anyway. If someone achieved something, they left the achievement behind for others to see, so it's exchangeable in that direction. 成績 you translated as achievement, but result or record would fit better here (based on literal meaning).

So I would go for "Achieve legendary results in the Taurus Hai" here, and similarly adjust all the others below this line too.

2021-06-10 07:28 UTC, robflop commented on src/data/uma-nickname-requirements.csv
> +"皐月賞、菊花賞、有馬記念（クラシック級）、天皇賞（春）を\n作戦「逃げ」で勝利し、うち菊花賞はスタート200m地点から\nゴールまで1番手のままで勝利する。","<size=22>As a runner, win the Satsuki Sho, Kikka Sho, Arima Kinen (2nd year), and Tenno Sho (Spring).\nIn the Kikka S
The "need to" at the end can be removed here to shorten it a bit and still stay accurate.

2021-06-10 07:28 UTC, robflop commented on src/data/uma-title.csv
> +"[あおぐもサミング]","[Blue Sky Thumbing]"
あおぐも (青雲, which can also be read as せいうん, hah) has a secondary meaning here as "high rank" or "erudition", but i'd keep it translated as "Blue Sky". The double meaning can't be made justice in english properly.

(To clarify, this is just a comment, not a request to change anything)

2021-06-10 07:34 UTC, stardustichi commented on src/data/trainer-title-requirements.csv
> +"タウラス杯で伝説的な成績を残そう","Leave a legendary achievement in the Taurus Hai"
makes sense, i was thinking the same but i doubted myself

2021-06-10 07:42 UTC, stardustichi commented on src/data/skill-desc.csv
> +"レース終盤のコーナーで先頭にいると\nこれ幸いと加速力を上げる","<size=22>On last corner, gain acceleration when leading in front</size>"
thanks, i had a feeling something is missing, just couldnt find the word!

2021-06-10 08:59 UTC, robflop commented on src/data/skill-desc.csv
> +"レース終盤のコーナーで先頭にいると\nこれ幸いと加速力を上げる","<size=22>On last corner, gain acceleration when leading in front</size>"
I'd personally change this to simply be "when in 1st place", words like "front" and "very front" still feel a bit vague.

Specifically, something like "When in 1st place in the last corner, gain acceleration".

2021-06-10 09:27 UTC, stardustichi commented on src/data/skill-desc.csv
> +"レース終盤のコーナーで先頭にいると\nこれ幸いと加速力を上げる","<size=22>On last corner, gain acceleration when leading in front</size>"
it should be good now right??

2021-06-10 11:44 UTC, FabulousCupcake commented on src/data/skill-desc.csv
> +"レース終盤のコーナーで先頭にいると\nこれ幸いと加速力を上げる","<size=22>On last corner, gain acceleration when leading in front</size>"
I'm late, but I think I started these terms; to me:
-  `leading` means being in the very front (`order<=1`)
- `in the front` means being in the front _side_ (`order_rate<=50`) or 
  - Same with `behind`
- `in the lead` means something like `order<=3` (i.e. top 3 lead)

We should probably document this somewhere for consistency and re-review all the existing translations.

2021-06-10 12:16 UTC, robflop commented on src/data/skill-desc.csv
> +"レース終盤のコーナーで先頭にいると\nこれ幸いと加速力を上げる","<size=22>On last corner, gain acceleration when leading in front</size>"
Good idea, i would follow this convention then and see about documenting it somewhere (via separate PR).

2021-06-11 12:14 UTC, FabulousCupcake commented
@robflop changes has been made; could you approve if there's anything else that needs to be updated?

2021-06-11 12:16 UTC, robflop requested changes

2021-06-11 12:16 UTC, robflop commented on src/data/uma-nickname-requirements.csv
> +"皐月賞、菊花賞、有馬記念（クラシック級）、天皇賞（春）を\n作戦「逃げ」で勝利し、うち菊花賞はスタート200m地点から\nゴールまで1番手のままで勝利する。","<size=22>As a runner, win the Satsuki Sho, Kikka Sho, Arima Kinen (2nd year), and Tenno Sho (Spring).\nIn the Kikka S
This is a bit off. 「200m地点から」means "from the 200m line on", so it should be "from the 200m line until the goal", or something like it.

2021-06-12 10:34 UTC, stardustichi commented on src/data/uma-nickname-requirements.csv
> +"皐月賞、菊花賞、有馬記念（クラシック級）、天皇賞（春）を\n作戦「逃げ」で勝利し、うち菊花賞はスタート200m地点から\nゴールまで1番手のままで勝利する。","<size=22>As a runner, win the Satsuki Sho, Kikka Sho, Arima Kinen (2nd year), and Tenno Sho (Spring).\nIn the Kikka S
that means i need to change the other one here somewhere as well, but lets save it for next time, when we do the translations re-review

2021-06-12 12:09 UTC, robflop approved these changes

2021-06-14 08:22 UTC, merged

2021-06-14 08:52 UTC, FabulousCupcake commented
🙌